from pydantic import BaseModel, Field
from typing import List

class QuestionDS(BaseModel):
    """
    Data Schema for QuestionDS
    """

    question: str = Field(..., title="Question", description="The question generated by the LLM")
